### ISSUE TITLE
[Feature] Set values for cloud_RoleName cloud_RoleInstance to Application Insights

### ISSUE THREAD

**Issue by MHHenriksen** [auth0-extensions/auth0-logs-to-provider#11]
See https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-map#nodejs for details and usecase.

For a regular ASP web app as well as a function app, `"ai.cloud.role"` and `"ai.cloud.roleInstance"` are by default set to the Azure resource name and the machine/vm id respectively. I'm thinking that good Auth0 equivalents would be tenant domain name and application/client name (or alternatively id, but I'd prefer to have something humanly recognisable)

**Comment by MHHenriksen** [comment]
Well, mr. bot, it would be nice to have a person look at it...

**Comment by MHHenriksen** [comment]
Still relevant

**Comment by MHHenriksen** [comment]
Still relevant

**Comment by MHHenriksen** [comment]
Still relevant. But this'll be the last time I refresh it. It's been a year. Neither me nor the maintainers have time to address it.

**Comment by machuga** [comment]
Hi, @MHHenriksen. I'm terribly sorry for the horrendous delay on this. That is on me.

Unfortunately we won't be making new additions to this extension, only bugfixes.

We have a new [Log Streaming](https://auth0.com/docs/logs/streams) system that we are migrating toward to better support exporting logs to systems like Application Insights. 

All that being said, I will be recording this into our product backlog so that this use case is known for additions in the Log Streaming system.

**Comment by MHHenriksen** [comment]
Thanks, appreciate the reply and closure :) I'll take a look at the log streaming.
