### ISSUE TITLE
Any plans for a sender to Sentry.io?

### ISSUE THREAD

**Issue by joaocc** [auth0-extensions/auth0-logs-to-provider#40]
We currently use sentry.io and would love to be able to integrate logs from auth0. Any plans? Thx

**Comment by xer0x** [comment]
Hey @joaocc,

Sorry, I don't know if we have plans to add an Extension for Sentry.io. However, rather than waiting for Auth0, you have a couple ways to do it yourself.

You could use Auth0's [Hooks](https://auth0.com/docs/hooks) and it looks like there is a Sentry.io npm package [available on the service](https://auth0-extensions.github.io/canirequire/#sentry). 

Better yet, you could use Auth0's [Log streaming](https://auth0.com/docs/logs/streams) service to integrate with Sentry.io. Log streaming provides support for [HTTP webhooks](https://auth0.com/docs/logs/streams/http-event) or [Amazon EventBridge](https://auth0.com/docs/logs/streams/aws-eventbridge). You'd need to setup your own service to forward the events on to Sentry.io.

**Comment by joaocc** [comment]
Thx for answering. Unfortunately we will not have the time or resources to implement that ourselves. 
In addition, and this is more a opinion, with sentry and auth0 being commercial companies, we would be looking into either (or both) of them collaborating to make this happen and have the required quality.

**Comment by machuga** [comment]
@joaocc Thanks for the feedback!

We're very interested in better understanding your use-case. 

If you're down to chat about your team's use case with Sentry, our team would be interested in learning more about the integration you envision.

**Comment by joaocc** [comment]
Thx.
We have a platform that is currently sending data to Sentry (vue, with C# on api, and C# on desktop).
We use auth0 for user authentication, and would like to have auth0 send information to the same Sentry systems where we already have the remaining events.

**Comment by machuga** [comment]
Would you be open to a phone call with our team? If so, can you send me an email at machuga@auth0.com and I'll get something scheduled? We have additional questions on use-case, functionality, etc.
