### ISSUE TITLE
Export of logging has stopped in production with no warning/errors

### ISSUE THREAD

**Issue by edmondo1984** [auth0-extensions/auth0-logs-to-provider#49]
In our production environment, we see that the logs are not pushed to Cloudwatch although we have events and the extension didn't provide any error. Can you please help?
![Screenshot 2020-04-08 at 13 53 24](https://user-images.githubusercontent.com/812841/78781340-5c63e400-79a0-11ea-9cd7-96b29c9f00c3.png)

**Comment by machuga** [comment]
Hi @edmondo1984! To confirm, you don't see any logs in Cloudwatch at all?

**Comment by edmondo1984** [comment]
It worked fine, and then at a certain date it is not pushing the logs
anymore (see the screenshot: Last update in april, last push in march)

Il giorno gio 9 apr 2020 alle ore 03:00 Matt Machuga <
notifications@github.com> ha scritto:

**Comment by machuga** [comment]
Right. You've verified the logs aren't in Cloudwatch, the last update timestamp is recent, but the log of attempted runs are not working. Is this correct?

I recommend attaching the Realtime Webtask Logs extension and monitoring for when your extension runs to see if it throws any errors to rule out something like an auth token or something similar failing. These should be recorded by the extensions nonetheless, but it is likely the next step in diagnosing.

**Comment by edmondo1984** [comment]
If you look to the last time on the top right, you can see it's 8 april, if you see the entries the last one is from 31 march. The problem is that "there are no additional entries"

**Comment by machuga** [comment]
> If you look to the last time on the top right, you can see it's 8 april, if you see the entries the last one is from 31 march. The problem is that "there are no additional entries". 

Correct, I understand this. I am asking more specifically that you have confirmed there are no logs in your Cloudwatch dashboard. If there are logs in your CW then it helps us understand it's the extension's status tracking. If you do *not* have logs in CW, then it is something that would need diagnosed with the Realtime Webtask Logs.

> The logs from the webtask are empty

They will be empty until the job fires. Did you leave it open for at least 10 minutes?

**Comment by edmondo1984** [comment]
It is not showing anything related to logs, 
```

12:59:24 PM:
 Connected
1:01:37 PM:
 new webtask request
1:01:37 PM:
 decision-creator
1:01:37 PM:
 finished webtask request
1:19:24 PM:
 Connected
1:21:15 PM:
 new webtask request
1:21:15 PM:
 decision-creator
1:21:15 PM:
 finished webtask request
```

**Comment by machuga** [comment]
Hmmm. Okay so at this point I think I'd recommend recording the latest checkpoint, reinstalling the extension, and having it pick back up from your last recorded checkpoint.

If this doesn't work I'd recommend raising a support ticket from your impacted tenant so that the support team and our engineers can review it further.

I'm terribly sorry you're experiencing this issue and hope we can get it resolved quickly.

I'm going to close out this issue since there's no further debugging I can recommend without needing private information.

**Comment by edmondo1984** [comment]
Thanks a lot for your help Matt, the ticket is already open with the
customer service.
 I am afraid that uninstall and reinstalling is not a viable solution for
such a critical feature such as audit logs: the export has stopped working
and we found out "randomly". Maybe I can provide them the logs from the
extension?

Thanks

Il giorno gio 9 apr 2020 alle ore 16:17 Matt Machuga <
notifications@github.com> ha scritto:

**Comment by machuga** [comment]
@edmondo1984 As long as you have your latest checkpoint recorded, there is no risk in uninstalling/reinstalling the extension because you can set the checkpoint and it will pick up from that location when it resumes.

However, I completely understand the concern and will reach out to support to see if I can track down your ticket. Thanks!
